CREATE TABLE IF NOT EXISTS baby_names(id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, gender TEXT, description TEXT, my_list INTEGER);
INSERT INTO baby_names(name, gender, description ) VALUES ('Simon', 'M', 'Simon: It means "he heard," "hearer." Simon is the French, English, and German variant of Simon. Simon, name of Hebrew origin, arises from Hebrew');
INSERT INTO baby_names(name, gender, description) VALUES ('Jorge', 'M','Jorge: Jorge originates from the Greek name Georgios, which derives from the word georgós, which is formed by the union of the terms ge, which means "earth" and erghon, meaning "work", meaning "he who works on the earth" farmer".');
INSERT INTO baby_names(name, gender, description) VALUES ('Max', 'M','Max: Means "the greatest", or "the highest" and is a name from the Latin Maximus');
INSERT INTO baby_names(name, gender, description) VALUES ('Zebilon', 'M','Zebilon: House of the richest.');
INSERT INTO baby_names(name, gender, description) VALUES ('Vicente', 'M','Vincent: It means "what is winning", "what wins", "who conquers", "winner, conqueror".');
INSERT INTO baby_names(name, gender, description) VALUES ('Lorenzo', 'M','Lorenzo: It means "natural of Laurento" or "inhabitant of Laurento".');
INSERT INTO baby_names(name, gender, description) VALUES ('Theo', 'M','Theo: It means "god", "God supreme".Theo is a proper name of Greek origin. It arises from théos, whose literal sense is "deus".');
INSERT INTO baby_names(name, gender, description) VALUES ('Pietro', 'M','Pietro: It means: "stone", "rock" or "firm". Pietro is considered the Italian version of the name Peter, who was historically known to have been one of the alleged apostles of Jesus Christ.');
INSERT INTO baby_names(name, gender, description) VALUES ('Luca', 'M','Luca: It means "the one who brings the light", "luminous", "bright" or "the inhabitant of Lucania.Luca is an Italian variant of the Latin name Lucas, which in turn originated from the Greek, loukás and Loukanos, meaning "from Lucania" or "Lucanus".');
INSERT INTO baby_names(name, gender, description) VALUES ('Miguel', 'M','Michael: It means "who is like God?". Michael is a masculine name and has its origin in the Hebrew Mikhael, formed from the junction of the mikhayáh elements, and El, meaning "who is like God?".');
INSERT INTO baby_names(name, gender, description) VALUES ('Artur', 'M','Arthur: Means "bear man," "bear king," "strong," "noble," or "brave." With Celtic origin and more specifically in Gaelic, the name Arthur derives from Arthur.');
INSERT INTO baby_names(name, gender, description) VALUES ('Davi', 'M','David: It means "the beloved", "dear", "favorite". It comes from the Hebrew name Dawid, Dawidh, meaning "the beloved," "beloved," "favorite."');
INSERT INTO baby_names(name, gender, description) VALUES ('Bernardo', 'M','Bernardo: It means "strong as a bear." The name Bernardo is formed by the junction of the Germanic elements ber, which means "bear", and hart, which means "strong."');
INSERT INTO baby_names(name, gender, description) VALUES ('Bruno', 'M','Bruno: Means "brown", "brown", "tan", "brown". Bruno is a name with two possibilities of origin, both of which refer to the same meaning. So much may have come from the Latin brunus, as from the German brun, which literally means "brown" or "brown."');
INSERT INTO baby_names(name, gender, description) VALUES ('Guilherme', 'M','Guilherme: It means "determined protector" or "brave protector". Guilherme has its origin in the Germanic name Willahelm, composed by the union of the elements will, vilja, wailja, which means "will, desire", and helm, hilms, which means "protection, helmet". It means "decided shield" or "courageous shield".');
INSERT INTO baby_names(name, gender, description) VALUES ('Eduardo','M', 'Eduardo: It means "guardian of the riches", "protector of the riches" or "rich guardian". It comes from the Germanic name Hadaward, composed by the junction of the elements ead, that means "rich, prosperous", and weard, ward, that means "guardian, guardian".');
INSERT INTO baby_names(name, gender, description) VALUES ('Felipe', 'M','Felipe: It means "friend of the horses", "that likes the horses", "that loves the war". Felipe originates in the Greek name Phílippos, formed by the junction of the words phílos, which means "amigo", and híppos, that means "horse". It means "friend of horses". By extension, it is given the meaning of "he who loves war."');
INSERT INTO baby_names(name, gender, description) VALUES ('Flavio', 'M','Flávio: It means "blond", "golden", "yellow" or "golden hair". The name Flávio originates from the Latin Flavius, which in turn originated from the word flavus, which means "yellow", "golden" or blond ", in reference to the color of the hair.');
INSERT INTO baby_names(name, gender, description) VALUES ('Heitor', 'M','Hector: Means "he who guards," "he who holds the enemy." It originates in the Greek Héktor, from the root ekhein, which means "I possess, I have in my power".');
INSERT INTO baby_names(name, gender, description) VALUES ('Samuel', 'M','Samuel: It means "Name of God." The name Samuel comes from the Hebrew Shemuel, which literally means "his name is God." The first element is related to the Aramaic shem, shema, shum, which means "name," and the second, El, means "God, Lord."');
INSERT INTO baby_names(name, gender, description) VALUES ('Henrique', 'M','Henrique: It means "lord of the home", "prince of the home" or "ruler of the house". Henrique originates in the Germanic name Haimirich, composed by the union of the elements heim, which means "home", "house", and rik, which means "lord", "prince", "power". From this junction comes the meaning "lord of the home," "prince of the home," or "ruler of the house."');
INSERT INTO baby_names(name, gender, description) VALUES ('Luiz', 'M','Luiz: It means "glorious fighter", "famous warrior" or "famous in war". Luiz is a variant of Luís, name originated in the Germanic Hloddoviko, Chlodovech. It is formed by the union of the elements hlot, hlut, meaning "famous, illustrious, famous," and wig, which means "warrior."');


INSERT INTO baby_names(name, gender, description) VALUES ('Alícia', 'F', 'Alícia: It means "of noble quality", "of noble lineage", "of noble blood"; "respected", "majestic". Alicia is a variation of the name Alice, name of Germanic origin that arises as a diminutive of Adelaide.');
INSERT INTO baby_names(name, gender, description) VALUES ('Flora', 'F', 'Flora: It means "florida", by extension, "full of beauty", "perfect". The name Flora comes from the Latin Flora, which derived from flower, floris and means "florida", "full of flowers".');
INSERT INTO baby_names(name, gender, description) VALUES ('Ágatha', 'F', 'Agatha: It means "good, perfect, respectable, virtuous". It arose from the Greek names Agathe and Agathós, which in turn have their origin in the Greek word agathos, meaning "good, perfect, respectable, virtuous."');
INSERT INTO baby_names(name, gender, description) VALUES ('Valentina', 'F', 'Valentina: It means "brave", "strong", "vigorous", "full of health". The name Valentina is Valentinians female variant, Valentino, which comes from the Latin name Valentinus.');
INSERT INTO baby_names(name, gender, description) VALUES ('Pietra', 'F', 'Pietra: It means "stone", "rock" or "firmness". Pietra is a beautiful Italian name, whose origin is Greek, and means "stone".');
INSERT INTO baby_names(name, gender, description) VALUES ('Manuela', 'F', 'Manuela: It means "God is with us" or "God with us". Manuela is the feminine form of Manuel, a variant of Emanuel, name originated from the Hebrew Immanuel.');
INSERT INTO baby_names(name, gender, description) VALUES ('Beatriz', 'F', 'Beatriz: It means "the one who brings happiness", "the one who makes others happy" or "traveler", "pilgrim." Beatriz originates from the Latin beatus, which means "happy", or in the Latin Beatrice, of beare, which means "that brings happiness" or "that which makes others happy."');
INSERT INTO baby_names(name, gender, description) VALUES ('Laura', 'F', 'Laura: It means "laurel", "victorious", "triumphant". Laura is the feminine of Lauro and originates in the Latin noun laurus, which means "laurel, laurel".');
INSERT INTO baby_names(name, gender, description) VALUES ('Heloísa', 'F', 'Heloisa: It means "healthy," "healthily broad," "glorious combatant," "famous warrior," "famous in war." means "healthy," and wid, which means "broad."');
INSERT INTO baby_names(name, gender, description) VALUES ('Cecilia', 'F', 'Cecilia: It means "blind", "wise" or "the guardian of musicians". Cecilia comes from the Roman family name Caecilius, from the Latin word caecus, meaning "blind."');
INSERT INTO baby_names(name, gender, description) VALUES ('Patricia', 'F', 'Patricia: It means "noble", "noble class", "from the same homeland" or "compatriot." Patrícia originates from the Latin name Patricius, which means "patrician", "noble", and was attributed those who represented the nobility in the civilization of ancient Rome.');
INSERT INTO baby_names(name, gender, description) VALUES ('Sofia', 'F', 'Sofia: It means "wisdom" or "the wise". The name Sofia came from the Greek sophia, which literally means "wisdom." It can also be translated as "the Word" (holiness) in its feminine form.');
INSERT INTO baby_names(name, gender, description) VALUES ('Maria', 'F', 'Mary: It means "sovereign lady," "seer" or "the pure." Mary is a name of uncertain origin, probably originated from the Hebrew Myriam, which means "sovereign lady" or "the seer."');
INSERT INTO baby_names(name, gender, description) VALUES ('Larissa', 'F', 'Larissa: It means "of the acropolis", "of the citadel"; "Beautiful", "lovely". Larissa is a name of Greek origin. It arises with the Pelasgians, who were the first inhabitants of Greece.');
INSERT INTO baby_names(name, gender, description) VALUES ('Júlia', 'F', 'Júlia: It means "fluffy", "soft", "young" or "daughter of Jupiter". Júlia is the feminine variant of Julius, name originated in the Latin Julius. Julius derives from the Greek Ioulos, which means "fluffy" or "soft", in reference to the facials of young people.');
INSERT INTO baby_names(name, gender, description) VALUES ('Isabela', 'F', 'Isabela: It means "caste," "pure," "God is an oath," or "consecrated to God." Isabela is a variant of the name Isabel, which has its origin in the Hebrew name Izebel, which means "caste, pure".');
INSERT INTO baby_names(name, gender, description) VALUES ('Ana', 'F', 'Ana: It means "graceful" or "full of grace." The name Anna comes from the original Hebrew Hannah, later the Latin Anna, which means "graceful, full of grace."');
INSERT INTO baby_names(name, gender, description) VALUES ('Camila', 'F', 'Camila: It means "messenger of the gods", "the priestess" or "girl of choir". Camilla is a female name that arose from the Latin Camillus, which meant "minister" or "priest in the sacrifices" among the Romans.');
INSERT INTO baby_names(name, gender, description) VALUES ('Joana', 'F', 'Joanna: It means "God is full of grace," "graced by God" or "the grace and mercy of God" and "God forgives." The name Joana has its origin in the Latin Iohanna and is the feminine variant of John from the Hebrew Yehokhanan, a result of the union of the elements Yah, "Yahweh, Jehovah, God", and hannah, "grace." Or RECONQUISTA HURRICANE');



CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, lastname TEXT,  signo TEXT, birthday TEXT);
